### ISSUE TITLE
Ensure that `useMediaQuery` has the "correct" initial value

### ISSUE THREAD

**Issue by Kyzegs** [react-hookz/web#1000]
### What is the new or updated feature that you are suggesting?

Ensure that `useMediaQuery` returns the matched value for the given query in the first render.

### Why should this feature be included?

In most cases, we do not want to load our animations on the initial page load. When we have a component with animations that relies on the `useMediaQuery` hook the following happens: The animation gets triggered because of the value from the hook changes. I've tried this with my animation implementation and libraries such as [Framer Motion](https://www.framer.com/motion/).

Having the correct initial value would fix this problem.

**Comment by Kyzegs** [comment]
I'll try to have an environment with the issue up later today.

**Comment by Kyzegs** [comment]
Here's the eEnvironment](https://stackblitz.com/edit/react-ts-fz7wbn?file=App.tsx) with the issue.

**Comment by ArttuOll** [comment]
I looked into this and I understand your problem. I'm currently trying to figure out a solution.

**Comment by kylemh** [comment]
I wanted to suggest reverting this and/or thinking about it more. I've just upgraded this package to the latest version and have to replace all my usages of `useMediaQuery` to include a second argument of `{ initializeWithValue: false }` in order to work in an SRR-based environment.

One suggestion might be to adjust [this line](https://github.com/react-hookz/web/pull/1020/files#diff-a4a82ae81629dbe9fe162c95cd2348f18617081fa3830992478adc9f02fa91fbR71):

`if (options?.initializeWithValue ?? true)` to be: `if (typeof window !== 'undefined' && (options?.initializeWithValue ?? true))`

I think this still appeases the original request without ruining the DX for people that use this hook with Next.js or Remix.

**Comment by xobotyi** [comment]
Your code will cause hydration error, since SSR state and browser one will differ.

**Comment by kylemh** [comment]
I see. I didn't think about strict mode... I'm not sure what the workaround is, but it really sucked to be punished by this change.

**Comment by xobotyi** [comment]
Overall - i've missed it during review, anyway since all other hook causes hydration error on missconfig rather than SSR crash.

@ArttuOll please, add `isBrowser` guard to the code so SSR at least works.

**Comment by ArttuOll** [comment]
No problem. I'll take a look later today.

**Comment by ArttuOll** [comment]
@kylemh Just wanted to let you know that we're working on this feature #1023 , which would improve DX for SSR significantly. It's still a WIP though - all help appreciated.
