### ISSUE TITLE
Import broken in latest major release 21.0

### ISSUE THREAD

**Issue by gurkerl83** [react-hookz/web#1067]
Import broken in latest major release 21.0.

I think it is related to the changes made in package.json in this commit
https://github.com/react-hookz/web/commit/5a622afe3f106036b807865faf6231ab20427113

Something that works
```
"type": "module",
"exports": {
   ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
   }
},
"types": "./dist/index.d.ts"
```

Not sure if the change is not required with Node 18 (does it support esnext properties in package.json? The version was also bumped from v16 to v18 in the commit. Mine is v16.13.0 and it does not work, also running with the latest NextJS version.

For reference https://www.typescriptlang.org/docs/handbook/esm-node.html

Thx!

**Comment by xobotyi** [comment]
As said in release notes - it is not broken, it just requires transpillation in case your bundler not able to handle esm without module typed package.

We're not switching to module package yet, since it is complete pain in the butt right now. Sadly not all tooling ready for it and we had to stop one step before it

BTW don't jump to latest version yet, tomorrow I'll merge #1065 it also has breaking changes. Today release is some bug in semantic-release module, it shouldn't have happen

**Comment by gurkerl83** [comment]
Understood, I will use latest v20 until the migration is complete. Please leave this issue open for others. I overlooked the comment in the release note, that v21 is an intermediate release with an additional transpilation step required along the way.

**Comment by xobotyi** [comment]
should be working with v22
