### ISSUE TITLE
Can't use `useCookieValue` since v24

### ISSUE THREAD

**Issue by nagisa-yamato** [react-hookz/web#1516]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

- https://github.com/react-hookz/web/issues/659

### What is the current behavior?

What does `@react-hookz/web` do right now.

- Can not import `useCookieValue`

### Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.

1. Try to `import { useCookieValue } from "@react-hookz/web"`
   - I've tried the import paths below

```ts
// Module '"@react-hookz/web"' has no exported member 'useCookieValue'.(2305)
import { useCookieValue } from '@react-hookz/web';
// Cannot find module '@react-hookz/web/useCookieValue/index.js' or its corresponding type declarations.(2307)
import { useCookieValue } from '@react-hookz/web/useCookieValue/index.js';
// Cannot find module '@react-hookz/web/esm/useCookieValue' or its corresponding type declarations.(2307)
import { useCookieValue } from '@react-hookz/web/esm/useCookieValue';
```

#### Demo

- https://stackblitz.com/edit/stackblitz-starters-x6httv?file=src%2FApp.tsx

### What is the expected behavior?

What should `@react-hookz/web` be doing?

- Import for `useCookieValue` is working, or docs are updated to show the correct import path
  - https://react-hookz.github.io/web/?path=/docs/side-effect-usecookievalue--example#importing

### Environment Details

- _`@react-hookz/web` version: 24.0.4_
- _`react` version: 18.2.0_
- _`react-dom` version: 18.2.0_
- _`typescript` version: `StackBlitz` -> `react-scripts` ?_
- _OS: `StackBlitz`_
- _Browser: `StackBlitz`_
- _Did this work in previous versions?_
  - works on **v23**

**Comment by 2snEM6** [comment]
This is happening to me as well!

**Comment by xobotyi** [comment]
If you address readme/changelog - package switched to ESM and doesn't have /esm folder anymore.
Documentation site is broken at the moment so imports there are outdated, you have to import this hook directly like this `import {useCookieValue} from '@react-hookz/web/useCookieValue/index.js';`

**Comment by xobotyi** [comment]
Documentation page is currently broken, thus havent been updated, it is true.

I dont know whats the matter with stackblitz and why it about non-existent issue with typescript.
My IDE (phpstorm) with TS 5.3.3 dont see any issue in import 
![image](https://github.com/react-hookz/web/assets/6178739/6e2a1a41-eb42-4cb8-8e48-ce7a5b1b01aa)

Moreover stackblitz despite having import underlined perfectly compiles everything🤔 https://stackblitz.com/edit/stackblitz-starters-lfd8ma?file=src%2FApp.tsx

**Comment by xobotyi** [comment]
Since typescript handles everything fine, but IDE not - i suspect that stackblitz (and codesandbox, as figures) has different, older version of typescript used for IDE purposes (same as vscode has own internal version of typescript used for language server purposes). Presumably it worth of creating bugreport there (stackblitz/codesandbox)🤔
`ts-ignore` will silence your IDE but it will also silence any possible future errors for actual compiler which is.. well.. debatable overall but is a temporal solution hat will work.

**Comment by xobotyi** [comment]
My guesses seems to be correct: https://github.com/stackblitz/core/issues/2944

**Comment by xobotyi** [comment]
Okay, sorry for loosing track of this one.

It is related to module resolution within your `tsconfig.json` being set to `node` which does not support `expors` directive which this package utilizes.

In case of need to keep `node` module resolution - you have to import file directly with full path to file, which would be `@react-hookz/web/dist/useCookieValue/index.js` (in recent v25 release `src` been replaces with with `dist` folder).
Proof with suck change of your recent repo:
![image](https://github.com/user-attachments/assets/448cd6e8-68ec-4e88-8664-2a8df28df625)

Otherwise I would recommend on using `NodeNext` or `Bindler` resolution values as supporting most recent `package.json` features.

Once again sorry for not responding such a long time.

Closing issue as solved.
