### ISSUE TITLE
useConditionalEffect should have a render count along with `conditions`

### ISSUE THREAD

**Issue by fcisio** [react-hookz/web#158]
## New Features

`useConditionalEffect` should have a render count along with `conditions`

### What is the new or updated feature that you are suggesting?

```jsx
useConditionalEffect(() => {
  // Run the effect once, only if `lib` is loaded
},
[lib],
({ count }) => lib != null && count === 0
)
```

### Why should this feature be included?

The `count` value could be used to limit the number of time the effect can run

**Comment by xobotyi** [comment]
There is not much sense in this counter since predicate should be holding previous conditions value and have handles to reset the counter, it is unnecessary overcomplication IMO.
Besides the fact that i dont really get where youll need implementation like 'execute callback every 3rd render when conditions all truthy'.

Other that that it is better to do such implementation with external renders counter, it will keep `useConditionalEffect` simple and versatile.

**Comment by xobotyi** [comment]
I'd prefer to implement #157  and mark this as wontfix
