### ISSUE TITLE
[getResizeObserver()]: ReferenceError: Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by fcisio** [react-hookz/web#291]
### What is the current behavior?

Hooks using `getResizeObserver()` are breaking on the latest IOS devices.
From what I was able to gather, a polyfill is required on some of those IOS devices.

> ReferenceError: Can't find variable: ResizeObserver

### Fix ✅ 

I was able to fix it with a polyfill, but it would be better and more reliable to **[ponyfill](https://www.npmjs.com/package/resize-observer)** `ResizeObserver` on here internally.

Edit: I realized that the IOS version I'm testing on is outdated. It would still be worth it to polyfill as it's only been about a year since it [got support on Safari Ios](https://caniuse.com/resizeobserver)

### Steps to Reproduce

I am unsure about the exact devices, but I am testing on iPad Pro 12.1

1. Add a hook that uses `ResizeObserver` (`useResizeObserver`, `useMesure`)
2. Serve to the device

### What is the expected behavior?

The project should run without bugs and warnings

### Environment Details

- _`@react-hookz/web` version:_ 7.0.0
- _`react` version:_ 17.0.2
- _`react-dom` version:_ 17.0.2
- _Browser:_ All IOS Browsers
- _Did this work in previous versions?_ No

**Comment by xobotyi** [comment]
Absolutely disagree, poyfilling is on developer side (and apple's unwilling to follow strandards is totally not the problem of library🙃)
Most of developers a) will not use this hook at all b) dont need built-in polyfills since targeting browsers that supports it.

To polyfill it by hand you only have to import polyfills before any other library (on the very top of index file) 4ex: [resize-observer-polyfill](https://www.npmjs.com/package/resize-observer-polyfill) or [@juggle/resize-observer](https://www.npmjs.com/package/@juggle/resize-observer)
